### ISSUE TITLE
Change all routes to start with api/

### ISSUE THREAD

**Issue by myasonik** [pkbigmarsh/Gen-Con-Buddy-API#1]
Just makes it easier for me, and I figure it probably doesn't impact you

**Comment by pkbigmarsh** [comment]
Fixed with https://github.com/pkbigmarsh/Gen-Con-Buddy-API/commit/00bb351a6fecd55f2079f970bc1950b822bef068

**Comment by pkbigmarsh** [comment]
Fixed by https://github.com/pkbigmarsh/Gen-Con-Buddy-API/commit/00bb351a6fecd55f2079f970bc1950b822bef068
