### ISSUE TITLE
gameMasters field doesn't exist

### ISSUE THREAD

**Issue by myasonik** [pkbigmarsh/Gen-Con-Buddy-API#4]

**Comment by pkbigmarsh** [comment]
That is correct. gameMasters never existed. The field is `gmNames`.

Might be worth calling out here about the field changes in 2024:

**Fields removed**
* Year
* Also Runes
* Materials Provided
* Prize
* Rules Complexity
* Original Order

** Fields Added**
* Materials Required `materialsRequired`
* Materials Required Details  `materialsRequiredDetails`

** Enums Added**
* Type
    * `TDA` - True Dungeon Adventures
    * `SPA` - Supplemental Activities
    * `EGM` - Electronic Games
* Registration
    * `generic` - "No, this is a generic ticket-only event!"
    * `tradeDay` - "Trade Day only!"
