### ISSUE TITLE
website field search is broken

### ISSUE THREAD

**Issue by myasonik** [pkbigmarsh/Gen-Con-Buddy-API#5]
https://pacific-plains-10689-8ac0e606559a.herokuapp.com/api/events/search?website=discord

But if you look through the data, there are games that have discord URLs

**Comment by pkbigmarsh** [comment]
duplicate of #6

**Comment by myasonik** [comment]
My bad

The other issues should have said email field, not website 🤦🏼

**Comment by myasonik** [comment]
I fixed that one but you should reopen this one

**Comment by pkbigmarsh** [comment]
fixed with [17d796a](https://github.com/pkbigmarsh/Gen-Con-Buddy-API/commit/17d796ad44be9b7e625613952923021e8a1757a2)
