### ISSUE TITLE
Maybe you? Maybe me? Dates are hard

### ISSUE THREAD

**Issue by myasonik** [pkbigmarsh/Gen-Con-Buddy-API#7]
Not sure if this is me or you but it 500s

https://pacific-plains-10689-8ac0e606559a.herokuapp.com/api/events/search?startDateTime=%5B2021-09-19T10%3A17%2C%5D

I think this is correct?

**Comment by pkbigmarsh** [comment]
This is wrong, you provided `2021-09-19T10:17Z,` which has two issues. The first is that it's attempting to be a range query, but not actually. A range query needs to be enclosed in brackets. So `[2021-09-19T10:17Z,]` would be an inclusive range.

The other issue is the wrong date format. You're missing seconds, `[2021-09-19T10:17:00Z,]` would be the correct search term. https://pacific-plains-10689-8ac0e606559a.herokuapp.com/api/events/search?startDateTime=[2021-09-19T10:17:00Z,]

**Comment by pkbigmarsh** [comment]
closing for user error
