### ISSUE TITLE
All fields need to be nested in an attributes object

### ISSUE THREAD

**Issue by myasonik** [pkbigmarsh/Gen-Con-Buddy-API#9]
Example response should look like:

```
data: [
  id: '123',
  type: 'event',
  attributes: {
    name: 'Twilight Imperium',
    gameId: '123',
    // etc
  }
],
// etc
```

You can compare against https://mirage.gcb.quest/search

You won't see the requests in the network panel because it's using the mock server, but they all get printed out to the console

**Comment by pkbigmarsh** [comment]
fixed with https://github.com/pkbigmarsh/Gen-Con-Buddy-API/commit/59de253da04f58090f2936ed99d695fc4ac81864
